version: 0.2

phases:
  install:
    commands:
      # install node and npm
      - apt update
      - apt install -y nodejs node-gyp
      - apt install -y npm
  pre_build:
    commands:
      # install dependencies
      - echo Installing Dependies
      - npm i
      - npm audit fix
  build:
    commands:
      # start and build
      - echo Testing..
      - npm run test
      - echo Building...
      - npm run build

artifacts: 
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
      
